FROM python:3.10-slim

WORKDIR /app

COPY proto/ proto/
COPY app/ app/
COPY requirements.txt .

RUN pip install -r requirements.txt
RUN python -m grpc_tools.protoc -Iproto --python_out=app --grpc_python_out=app proto/raft.proto

ENV PYTHONPATH=/app
CMD ["python", "-u", "app/raft_node.py"]