# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: swim.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'swim.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nswim.proto\x12\x04swim\",\n\x08NodeInfo\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"E\n\x0bPingRequest\x12\x1e\n\x06sender\x18\x01 \x01(\x0b\x32\x0e.swim.NodeInfo\x12\x16\n\x0etarget_node_id\x18\x02 \x01(\t\".\n\x0cPingResponse\x12\r\n\x05\x61live\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"K\n\x0ePingReqRequest\x12!\n\trequester\x18\x01 \x01(\x0b\x32\x0e.swim.NodeInfo\x12\x16\n\x0etarget_node_id\x18\x02 \x01(\t\"1\n\x0fPingReqResponse\x12\r\n\x05\x61live\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\".\n\x14\x44isseminationMessage\x12\x16\n\x0e\x66\x61iled_node_id\x18\x01 \x01(\t\"/\n\x0bJoinRequest\x12 \n\x08new_node\x18\x01 \x01(\x0b\x32\x0e.swim.NodeInfo\"7\n\x0cJoinResponse\x12\'\n\x0fmembership_list\x18\x01 \x03(\x0b\x32\x0e.swim.NodeInfo\"B\n\x17MembershipUpdateRequest\x12\'\n\x0fmembership_list\x18\x01 \x03(\x0b\x32\x0e.swim.NodeInfo\"\x07\n\x05\x45mpty2\xbd\x01\n\x0f\x46\x61ilureDetector\x12-\n\x04Ping\x12\x11.swim.PingRequest\x1a\x12.swim.PingResponse\x12;\n\x0cIndirectPing\x12\x14.swim.PingReqRequest\x1a\x15.swim.PingReqResponse\x12>\n\x10UpdateMembership\x12\x1d.swim.MembershipUpdateRequest\x1a\x0b.swim.Empty2v\n\rDissemination\x12\x36\n\x0b\x44isseminate\x12\x1a.swim.DisseminationMessage\x1a\x0b.swim.Empty\x12-\n\x04Join\x12\x11.swim.JoinRequest\x1a\x12.swim.JoinResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'swim_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NODEINFO']._serialized_start=20
  _globals['_NODEINFO']._serialized_end=64
  _globals['_PINGREQUEST']._serialized_start=66
  _globals['_PINGREQUEST']._serialized_end=135
  _globals['_PINGRESPONSE']._serialized_start=137
  _globals['_PINGRESPONSE']._serialized_end=183
  _globals['_PINGREQREQUEST']._serialized_start=185
  _globals['_PINGREQREQUEST']._serialized_end=260
  _globals['_PINGREQRESPONSE']._serialized_start=262
  _globals['_PINGREQRESPONSE']._serialized_end=311
  _globals['_DISSEMINATIONMESSAGE']._serialized_start=313
  _globals['_DISSEMINATIONMESSAGE']._serialized_end=359
  _globals['_JOINREQUEST']._serialized_start=361
  _globals['_JOINREQUEST']._serialized_end=408
  _globals['_JOINRESPONSE']._serialized_start=410
  _globals['_JOINRESPONSE']._serialized_end=465
  _globals['_MEMBERSHIPUPDATEREQUEST']._serialized_start=467
  _globals['_MEMBERSHIPUPDATEREQUEST']._serialized_end=533
  _globals['_EMPTY']._serialized_start=535
  _globals['_EMPTY']._serialized_end=542
  _globals['_FAILUREDETECTOR']._serialized_start=545
  _globals['_FAILUREDETECTOR']._serialized_end=734
  _globals['_DISSEMINATION']._serialized_start=736
  _globals['_DISSEMINATION']._serialized_end=854
# @@protoc_insertion_point(module_scope)
